"""
Generate Paper Data

This script bridges the gap between the live Sema graph and the static LaTeX paper.
It calculates statistics and outputs a `sema_stats.tex` file that can be \input{} into the paper.

Usage:
    python scripts/export/generate_paper_data.py > papers/sema_stats.tex

In the paper (sema.tex):
    \input{sema_stats.tex}
    ...
    \newcommand{\SemaTotalPatterns}{316} % Defined in stats file
"""

import json
import os
import statistics

VOCAB_DIR = 'data/vocabulary'

def generate_tex_stats():
    if not os.path.exists(VOCAB_DIR):
        return

    patterns = []
    for f in os.listdir(VOCAB_DIR):
        if f.endswith(".json"):
            with open(os.path.join(VOCAB_DIR, f), 'r') as file:
                try:
                    patterns.append(json.load(file))
                except:
                    pass

    total = len(patterns)
    
    # Calculate compression
    ratios = []
    for p in patterns:
        handle = p.get('handle', '')
        ref_len = len(handle) + 5
        mech = p.get('mechanism', '')
        inv = " ".join(p.get('invariants', []))
        def_len = len(mech) + len(inv)
        if ref_len > 0 and def_len > 0:
            ratios.append(def_len / ref_len)
            
avg_comp = statistics.mean(ratios) if ratios else 0

    print(f"% Generated by scripts/export/generate_paper_data.py")
    print(f"\\newcommand{{\\SemaTotalPatterns}}{{{total}}}")
    print(f"\\newcommand{{\\SemaCompressionRatio}}{{{avg_comp:.1f}}}")
    print(f"\\newcommand{{\\SemaUniqueMechanisms}}{{{total}}}") # Assuming all unique for now

if __name__ == "__main__":
    generate_tex_stats()
