#!/usr/bin/env python3
"""
Generate Pattern Cards LaTeX
Reads from vocabulary folder and generates pattern card specifications
for the paper appendix with full hashes (not truncated stubs).
"""

import json
import os

VOCAB_DIR = "data/vocabulary"
OUTPUT_PATH = "paper/generated_pattern_cards.tex"

# Patterns to include in the appendix (in order)
APPENDIX_PATTERNS = [
    "StateLock",
    "FractalIntelligence",
    "SpectralTune",
    "SteelmanCheck",
    "OptimisticSolver",
]


def load_vocab():
    """Load all vocabulary patterns and build a handle->data map."""
    vocab_data = {}
    for filename in os.listdir(VOCAB_DIR):
        if filename.endswith(".json"):
            filepath = os.path.join(VOCAB_DIR, filename)
            with open(filepath) as f:
                data = json.load(f)
                handle = data.get("handle")
                if handle:
                    vocab_data[handle] = data
    return vocab_data


def extract_full_hash(sema_id):
    """Extract the full hash from a sema_id string."""
    if "SHA-256:" in sema_id:
        return sema_id.split("SHA-256:")[1]
    return None


def format_reference(sema_id):
    """Keep the full sema_id format: sema:Handle#mh:SHA-256:hash."""
    # Already in full format, return as-is
    if sema_id.startswith("sema:") and "#mh:SHA-256:" in sema_id:
        return sema_id
    return sema_id


def format_card_for_latex(data):
    """
    Format a pattern card showing ONLY the semantic fields that get hashed.
    This is the canonical content that produces the Merkle root hash.

    Hashed fields (from hashing.py):
        dependencies, signature, data_schema, mechanism, gloss,
        invariants, preconditions, postconditions, parameters,
        failure_modes, extends (or the authored legacy derived_from key)

    NOT hashed: handle, _meta, sema_id, sema_ref, sema_stub, etc.
    """
    # Only include semantic fields - exactly what gets hashed
    semantic_fields = [
        "dependencies",
        "signature",
        "data_schema",
        "mechanism",
        "gloss",
        "invariants",
        "preconditions",
        "postconditions",
        "parameters",
        "failure_modes",
        "extends",
    ]

    card = {}
    if "extends" in data and "derived_from" in data:
        raise ValueError("Pattern cannot contain both extends and legacy derived_from")
    for field in semantic_fields:
        if field in data:
            card[field] = data[field]
    if "derived_from" in data:
        # Preserve the historical key verbatim; normalizing it to `extends`
        # would display different content from the bytes that produced the ID.
        card["derived_from"] = data["derived_from"]

    return json.dumps(card, indent=2)


def get_subsection_title(data):
    """Generate subsection title with full sema ID."""
    handle = data.get("handle", "Unknown")
    sema_id = data.get("sema_id", "")
    if sema_id:
        # Escape # for LaTeX: sema:Handle\#mh:SHA-256:hash
        return sema_id.replace("#", "\\#")
    return handle


def generate_pattern_cards():
    """Generate the pattern cards LaTeX file."""
    vocab_data = load_vocab()
    print(f"Loaded {len(vocab_data)} patterns from vocabulary.")

    lines = []
    lines.append("% Auto-generated pattern card specifications")
    lines.append("% Generated by generate_pattern_cards.py from vocabulary/*.json")
    lines.append("% DO NOT EDIT MANUALLY - changes will be overwritten")
    lines.append("")
    lines.append(
        "The following cards show the \\textbf{canonical hashed content} for each pattern."
    )
    lines.append(
        "Only semantic fields are included---these are the exact fields "
        "that produce the Merkle root hash."
    )
    lines.append(
        "Metadata fields (\\texttt{handle}, \\texttt{\\_meta}, \\texttt{tier}, etc.) "
        "are \\emph{not} part of the hash."
    )
    lines.append("")

    for handle in APPENDIX_PATTERNS:
        if handle not in vocab_data:
            print(f"Warning: Pattern '{handle}' not found in vocabulary")
            continue

        data = vocab_data[handle]
        title = get_subsection_title(data)
        json_str = format_card_for_latex(data)

        # Add tier note if Tier 2
        tier = data.get("_meta", {}).get("tier", 1)
        tier_note = ""
        if tier == 2:
            tier_note = (
                "\n\\textbf{Note}: This pattern was downgraded to "
                "\\textbf{Tier~2} following adversarial analysis.\n"
            )

        # Keep the full-ID heading with the opening lines of its card. These
        # headings often wrap, so ordinary section widow protection is not
        # enough near a page boundary.
        lines.append("\\Needspace{7\\baselineskip}")
        lines.append(f"\\subsection{{{title}}}")
        if tier_note:
            lines.append(tier_note)
        lines.append("")
        lines.append("\\begin{lstlisting}")
        lines.append(json_str)
        lines.append("\\end{lstlisting}")
        lines.append("")

        print(f"Generated card for {handle}")

    # Write output
    with open(OUTPUT_PATH, "w") as f:
        f.write("\n".join(lines))

    print(f"\nGenerated {OUTPUT_PATH}")


if __name__ == "__main__":
    generate_pattern_cards()
